"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取，在 Vercel 面板设置
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-s^=b5rj!-r5_*oc9g$e&3imcj1_ne(z1rswwz-v-vj)-gtwo17')

# 本地开发用 True，Vercel 部署自动读取 DEBUG=False
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'getshare.vercel.app',
    '.vercel.app',  # 匹配所有 Vercel 预览域名
    '127.0.0.1',
    'localhost',
]

# ========== 部署核心修改3：安全配置（防跨域/HTTPS） ==========
# 信任 Vercel 的 HTTPS 链接
CSRF_TRUSTED_ORIGINS = [
    'https://getshare.vercel.app',
    'https://*.vercel.app',
]
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    #我的应用程序
    'blog_context',
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 静态文件必须在第二位
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'blog' / 'static',
]
# 部署时收集所有静态文件到此目录
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise 压缩静态文件（仅在生产环境启用）
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 在 Vercel 上 DEBUG 默认为 True unless you explicitly set it in the
# project’s Environment Variables. 产线部署必须把 DEBUG=False 否则
#静态/媒体路径、缓存和安全设置不会生效。

# 我的设置
LOGIN_REDIRECT_URL = 'blog_context:posts'
LOGOUT_REDIRECT_URL = 'blog_context:posts'

AUTH_USER_MODEL = 'accounts.CustomUser'
# -------------------------- 媒体文件配置（头像上传必须） --------------------------
# 媒体文件根目录：所有上传的头像都会存在项目根目录的media文件夹下
MEDIA_ROOT = BASE_DIR / 'media'
# 媒体文件访问URL：前端通过 /media/avatars/2026/02/26/xxx.png 访问头像
MEDIA_URL = '/media/'

# ⚠️ Vercel 不会保留部署期间生成的本地文件。任何用户上传
# 内容如果写到 MEDIA_ROOT（例如头像、评论图片、文章配图）
# 在下一次构建或在函数休眠后就会消失，这就是线上“图片不显示”的
# 根源。生产环境的媒体请交由外部对象存储（Cloudinary、S3 等），
# 并在 settings.py 里设置相应的 DEFAULT_FILE_STORAGE。例如：
#
# if not DEBUG:
#     DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
#     CLOUDINARY_STORAGE = {
#         'CLOUD_NAME': os.environ['CLOUDINARY_CLOUD_NAME'],
#         'API_KEY': os.environ['CLOUDINARY_API_KEY'],
#         'API_SECRET': os.environ['CLOUDINARY_API_SECRET'],
#     }
#
# 或者把 MEDIA_URL 指向你自己的 CDN。只要不依赖本地 media/ 目录，
# 静态图片才能在 Vercel 部署时持续有效。
