# Generated by Django 6.0.2 on 2026-03-01 04:42

import blog_context.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_context", "0004_comment_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
        migrations.AddField(
            model_name="context",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=blog_context.models.post_image_upload_path,
            ),
        ),
    ]
