# Generated by Django 6.0.2 on 2026-02-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="电子邮箱"
            ),
        ),
    ]
