# Generated by Django 6.0.2 on 2026-03-01 04:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                upload_to=accounts.models.avatar_upload_path,
                verbose_name="用户头像",
            ),
        ),
    ]
